const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=__dirname;
const server=fs.readFileSync(path.join(root,'api/server.js'),'utf8');
const html=fs.readFileSync(path.join(root,'api/public/index.html'),'utf8');
const schema=fs.readFileSync(path.join(root,'database/schema.sql'),'utf8');
const mig=fs.readFileSync(path.join(root,'database/migrate_v6_7_ai_draft.sql'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'api/package.json'),'utf8'));
assert(server.includes("/api/clients/:id/ai-plan-draft"));
assert(server.includes("CREATE_AI_DRAFT_PLAN"));
assert(server.includes("workflow_status='DRAFT'"));
assert(server.includes("ai_intent"));
assert(html.includes('aiPlanDraftBtn'));
assert(html.includes('/ai-plan-draft'));
assert(schema.includes('ai_intent'));
assert(mig.includes('ADD COLUMN IF NOT EXISTS ai_intent JSONB'));
assert.strictEqual(pkg.version,'6.7.0');
assert(pkg.scripts.test.includes('test_v6_7.js'));
console.log('V6.7 draft workflow contract: PASS');
